### ISSUE TITLE
Some pseudosteno edge cases

### ISSUE THREAD

**Issue by hftf** [Kaoffie/plover_word_tray#1]
Sharing a few pseudosteno edge cases I detected and organized for ease of future reference. Thanks!

Pseudosteno rule | Fails on word pattern | Example word | Steno | Current pseudo | Expected | Notes
-|-|-|-|-|-|-
KP- → X- | -cc- as /ks/ | access | KPES | KPES | XES
-BGS → -X | -x- as /ks/ | execution | EBGS/KAOUGS | EKSHUN/KUUGS | EX/KUUSHUN | <details><summary></summary>execute is correctly EX/KUUT</details>
-BGS → -KSHUN | -xation- as /kseɪʃən/ | taxation | TA*EUBGS | T*AIX | T*AIKSHUN | <details><summary></summary>tricky as taxation includes X too /details>
PH- → M- |  comm- as /kə.m/ | commune | KPHAOUN | KPHUUN | KMUUN
PH- → M- |  pl- as /pl/ | simpler | SPHRER | SMRER | SPLER
STK- → DS- |  dec- as /dɨ.s/ | decision | STKEUGS | SDISHUN | DSISHUN
STKPW- → SG- | dis’g- as /dɪsɡ/ | distinguish | STKPWEUGS | DSBISH | SGISH | <details><summary></summary>also false positive for PW-: word has no `b`</details>
STKPW- → SG- | ag- as /əɡ/ | again | STKPWEPB | SDBEN | SGEN | <details><summary></summary>also false positive for TK- and PW-: word has no `d` or `b`/details>
-GS → -SHUN | -gion as /dʒən/ | region | RAOEGS | REEGS | REESHUN | <details><summary></summary>could consider a voiced allosuffix -JUN of pseudosteno -SHUN</details>
-GS → -SHUN | -shion as /ʃən/ | fashion | TPAGS | FAGS | FASHUN
-NGS → -SHUN | -nation as /n(eɪ)ʃən/ | donation | TKOENGS | DOENGS | DOENSHUN
-NGS → -SHUN | -ntion as /n(t)ʃən/ | mention | PHEPBGS| MENGS | MENSHUN
-RB → - SH | -rp as /rpʃən/ | absorption | SPWORBGS | SBOSHSHUN | SBORBSHUN
-RBG → - RK | -rk as /rk/ | dark | TKARBG | DASHG | DARK
-FRB → -RV | -ver as /v.r/ | everybody | EFRB | EFRB | ERV
-F → -V | -ver as /v.r/ | several | SEFRL | SEFRL | SEVRL
-F → -V | -ver as /v.r/ | silver | SEUFRL | SIFRL | SIVRL | <details><summary></summary>has `l`–`vr` inversion</details>
-FP → -CH | -sp’tion as /sp.ʃən/ | disposition | TKEUFPGS | DICHSHUN | DIFPSHUN | <details><summary></summary>false positive: word has no `ch` sound</details>
-FP → -CH | -sp’cion as /sp.ʃən/ | suspicion | SUFPGS | SUCHSHUN | SUFPSHUN | "
-FP → -CH | -st’nt as /st.ənt/ | resistant | REUFPBT | RICHBT | RIFNT | "
-FP → -CH | -f’n as /f.n/ | defend | TKEFPBD | DECHBD | DEFND | "
-FP → -CH | -sp as /sp/ | whisper | WHEUFP/*ER | WHICH/*ER | WHIFP/*ER | "
-FP → -CH | -pfl as /pfl/ | helpful | HEFPL | HECHL | HEFPL | "
-FP → -CH | acronym brief | evidence<br>based<br>medicine | PWEFPL | BECHL | BEFPL | "

**Comment by Kaoffie** [comment]
Heya, the mistakes you listed should be fixed now, except for a few things:
- absorption has "rp" but the outline contains RB, so it's kinda tricky.
- the FRB in "everybody" stands for the "-veryb-", so the pseudo is correct
- representing -F as V in pseudosteno would be confusing since V is represented by *F, with an asterisk

**Comment by hftf** [comment]
Thanks, very appreciated! Would you find more reports of these edge cases useful?

I think there was a copy-and-paste typo: on line 96, -RB outputs -SHG, but should be -SH. Re: the bullet list:

* Could maybe change `b` to `[bp]` in the BSHUN regex to handle this situation?
* Got it; for what it's worth, everywhere (WEFRB) has pseudosteno `WERV`, I noticed.
* Got it, for some reason I thought I'd seen `-V`'s in pseudosteno but now can't find any.

Communication still gives `KMUUNGS`, but I see it's tricky because of the intervening `-ic-` in `-n__ation`.

I see that many conditionals have a default case outputting pseudosteno, like `("", "RJ")`, but I'm wondering if they should at least pass a minimal test like "must include some type of j-sound" before outputting anything that's not raw? There would still be edge cases, but the trade-off shifts from "adding exceptions of what doesn't qualify as RJ" to "adding refinements of what counts a j-sound", as well as from users being confused when words are represented in pseudosteno with sounds they don't contain (false positives), to users being accepting of more false negatives but which already look like steno.

**Comment by Kaoffie** [comment]
I've made a few more tweaks based on the points you mentioned!

As for the conditionals having default cases that don't have tests, I'm not really sure about that - they were initially put there because they seemed to work fairly well most of the time, and helps the user to identify the exact stroke quicker than just a string of key labels, even if it's a false positive, so I think it is fairly useful - I could be wrong though, thinking about maybe making pseudosteno conversion customizable, but this plugin isn't at the top of my priorities so that may take a while.
